// Security headers on every response. CSP itself is generated by SvelteKit
// (see svelte.config.js) so its inline bootstrap script gets a nonce.
export async function handle({ event, resolve }) {
	const response = await resolve(event);
	response.headers.set('X-Content-Type-Options', 'nosniff');
	response.headers.set('X-Frame-Options', 'DENY');
	response.headers.set('Referrer-Policy', 'no-referrer');
	response.headers.set('Permissions-Policy', 'geolocation=(self), camera=(), microphone=(), payment=()');
	return response;
}
